# doc: https://github.com/redhat-plumbers-in-action/devel-freezer#readme
---

name: Development Freeze
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  freezer:
    runs-on: ubuntu-22.04

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Development Freezer
        uses: redhat-plumbers-in-action/devel-freezer@5e9a78c2c83f817e0c8386732f141e280d57c9e0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
